### ISSUE TITLE
OBSKorgNanokontrol2 becomes unresponsive after quickly moving sliders or knobs

### ISSUE THREAD

**Issue by smurphster** [C9Glax/OBSKorgNanokontrol2#8]
If you quickly move sliders or knobs up and down many times, the app just stops responding. No error is displayed. Buttons don't work either. I'll try to debug this one.

**Comment by C9Glax** [comment]
I have the same problem.
What I think might be the issue is the Windows Volume control, because before I added that it worked fine.
Tried to combat the issue with 
WindowsSoundControl > AudioDevice.cs
`
            if(timeelapsed > 1000 / this.maxDeviceActionsPerSecond)
`

What I think is happening is that there is a limit as to how often you can refresh those values...

**Comment by C9Glax** [comment]
Same goes for WebSocket...
Might want to add a buffer that updates every x-milliseconds...
